[package]
name = "rusty-fractals"
version = "0.1.0"
authors = ["fatalerrorcoded"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.32.2", features = [ "bundled", "static-link" ] }
gl = "0.13.0"